// crates/z-engine-gui/ui/src/components/chat/ActivityStrip.svelte
<script lang="ts">
  import { splitWork } from "$lib/toolGroups";
  import type { Msg } from "$lib/types";
  import Icon, { ChevronRight } from "$lib/ui/icons";
  import ActionCard from "./ActionCard.svelte";

  type Props = { items: Msg[] };
  let { items }: Props = $props();

  const parts = $derived(splitWork(items));
  let openIds = $state<Record<number, boolean>>({});

  function toggle(id: number) {
    openIds = { ...openIds, [id]: !openIds[id] };
  }
</script>

<div class="activity-strip">
  {#each parts as p}
    {#if p.type === "reason"}
      {@const body = p.msg.thinkingBody}
      {@const isStreaming = Boolean(p.msg.streaming)}
      {@const open = Boolean(openIds[p.msg.id])}
      <div class={`reason-line${isStreaming ? " streaming" : ""}`}>
        <button
          type="button"
          class="reason-btn"
          onclick={() => body && toggle(p.msg.id)}
          disabled={!body && !isStreaming}
        >
          <span class={`reason-chevron${open ? " open" : ""}`}>
            <Icon icon={ChevronRight} size={11} />
          </span>
          <span class="reason-label">
            {#if isStreaming}<span class="reason-pulse-dot" aria-hidden="true"></span>{/if}
            Reasoning
          </span>
          <span class="reason-text">{p.text || (isStreaming ? "thinking…" : "")}</span>
        </button>
        {#if open && body}
          <pre class="thinking-body">{body}</pre>
        {/if}
      </div>
    {:else}
      <ActionCard family={p.family} tools={p.tools} />
    {/if}
  {/each}
</div>

// crates/z-engine-gui/ui/src/components/ActivityStrip.tsx
import { useState } from "react";
import { ChevronRight } from "../lib/icons";
import { splitWork } from "../lib/toolGroups";
import type { Msg } from "../lib/events";
import { ActionCard } from "./ActionCard";

function ReasonLine({ msg, text }: { msg: Msg; text: string }) {
  const [open, setOpen] = useState(false);
  const body = msg.thinkingBody;
  const isStreaming = Boolean(msg.streaming);
  return (
    <div className={`reason-line${isStreaming ? " streaming" : ""}`}>
      <button
        type="button"
        className="reason-btn"
        onClick={() => body && setOpen((v) => !v)}
        disabled={!body && !isStreaming}
      >
        <span className={`reason-chevron${open ? " open" : ""}`}>
          <ChevronRight size={11} />
        </span>
        <span className="reason-label">
          {isStreaming && <span className="reason-pulse-dot" aria-hidden />}
          Reasoning
        </span>
        <span className="reason-text">{text || (isStreaming ? "thinking…" : "")}</span>
      </button>
      {open && body && <pre className="thinking-body">{body}</pre>}
    </div>
  );
}

/** Reasoning line + compact action cards for a turn's work. */
export function ActivityStrip({ items }: { items: Msg[] }) {
  const parts = splitWork(items);
  return (
    <div className="activity-strip">
      {parts.map((p) =>
        p.type === "reason" ? (
          <ReasonLine key={p.msg.id} msg={p.msg} text={p.text} />
        ) : (
          <ActionCard key={p.tools[0].id} family={p.family} tools={p.tools} />
        ),
      )}
    </div>
  );
}
