// crates/z-engine-gui/ui/src/components/overlays/PromptInspector.svelte
<script lang="ts">
  import { inspectPrompt, type PromptInspect } from "$lib/commands";
  import {
    categorizeRow,
    inspectBody,
    inspectCopyText,
    inspectRows,
    type ContextCategory,
  } from "$lib/promptInspectView";
  import { sessionStore } from "$lib/runtime";
  import Icon, {
    AlertTriangle,
    Brain,
    Check,
    ChevronLeft,
    Copy,
  } from "$lib/ui/icons";
  import { fmtTokens } from "$lib/util";
  import LogoMark from "../chrome/LogoMark.svelte";
  import WindowControlsMaybe from "../chrome/WindowControlsMaybe.svelte";
  import PromptInspectContent from "./PromptInspectContent.svelte";
  import PromptInspectSidebar from "./PromptInspectSidebar.svelte";
  import "../../settings.css";
  import "../promptInspect.css";

  type Props = { isClosing?: boolean; onClose: () => void };
  let { isClosing = false, onClose }: Props = $props();

  let snap = $state<PromptInspect | null>(null);
  let err = $state<string | null>(null);
  let loading = $state(true);
  let sel = $state(0);
  let copied = $state(false);
  let activeCategory = $state<ContextCategory | "all">("all");

  const rows = $derived(snap ? inspectRows(snap) : []);
  const activeRow = $derived(rows[sel] ?? rows[0]);

  // Context category token distribution
  const categoryStats = $derived.by(() => {
    const stats = {
      instructions: 0,
      project: 0,
      conversation: 0,
      capabilities: 0,
      total: snap?.totalTokens ?? 0,
    };
    if (!snap) return stats;
    for (const r of rows) {
      const cat = categorizeRow(r);
      const tok = r.kind === "msg" ? r.part.tokens : r.tool.tokens;
      stats[cat] += tok;
    }
    return stats;
  });

  // Estimated max context window for the active model (200,000 standard)
  const maxContext = 200_000;
  const memoryPct = $derived(
    categoryStats.total > 0
      ? Math.min(100, Math.round((categoryStats.total / maxContext) * 100))
      : 0,
  );

  const memoryStatus = $derived.by(() => {
    if (memoryPct < 40) return { text: "Plenty of room", color: "#00d68f" };
    if (memoryPct < 75) return { text: "Normal usage", color: "#38bdf8" };
    if (memoryPct < 90) return { text: "Getting full", color: "#f5a623" };
    return { text: "Near limit", color: "#ff453a" };
  });

  $effect(() => {
    loading = true;
    const id = sessionStore.getSnapshot() || undefined;
    inspectPrompt(id)
      .then((s) => {
        snap = s;
        err = null;
        sel = 0;
        loading = false;
      })
      .catch((e: unknown) => {
        err = String(e).replace(/^Error:\s*/, "");
        loading = false;
      });
  });

  $effect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") {
        e.preventDefault();
        onClose();
      }
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  });

  async function onCopyAll() {
    if (!snap) return;
    try {
      await navigator.clipboard.writeText(inspectCopyText(snap));
      copied = true;
      setTimeout(() => (copied = false), 1400);
    } catch (e) {
      console.error(e);
    }
  }
</script>

<div class={`settings-overlay${isClosing ? " is-closing" : ""}`} role="presentation">
  <div
    class={`settings-page prompt-inspect-page${isClosing ? " is-closing" : ""}`}
    role="dialog"
    tabindex="-1"
    aria-label="Context and memory inspector"
  >
    <header class="app-topbar settings-topbar" data-tauri-drag-region>
      <div class="topbar-left" data-tauri-drag-region>
        <button
          type="button"
          class="icon-btn settings-back-btn"
          title="Back (Esc)"
          onclick={onClose}
          aria-label="Back"
        >
          <Icon icon={ChevronLeft} size={15} strokeWidth={1.8} />
        </button>
        <div class="settings-breadcrumb">
          <span class="settings-breadcrumb-root">Context & Memory</span>
          {#if snap?.model}
            <span class="settings-breadcrumb-sep">/</span>
            <span class="prompt-model-badge" title={snap.model}>{snap.model}</span>
          {/if}
        </div>
      </div>

      <div class="topbar-center" data-tauri-drag-region>
        <div class="settings-topbar-pill">
          <LogoMark size={14} />
          <span>Active Context Inspector</span>
        </div>
      </div>

      <div class="topbar-right" data-tauri-drag-region>
        <button
          type="button"
          class="settings-copy-btn"
          onclick={() => void onCopyAll()}
          disabled={!snap}
          aria-label="Copy all context"
          title="Copy entire context and instructions to clipboard"
        >
          <Icon icon={copied ? Check : Copy} size={13} />
          <span>{copied ? "Context Copied" : "Copy All Context"}</span>
        </button>
        <WindowControlsMaybe />
      </div>
    </header>

    <div class="app-body settings-body prompt-inspect-body">
      <PromptInspectSidebar
        {rows}
        selected={sel}
        onSelect={(idx) => (sel = idx)}
        {activeCategory}
        onSelectCategory={(cat) => (activeCategory = cat)}
        {loading}
        {err}
      />

      <section class="canvas-pane settings-canvas-pane prompt-canvas-pane">
        <div class="settings-content-wrap">
          <div class="prompt-main-scrollable">
            {#if err}
              <div class="prompt-inspect-err" role="alert">
                <Icon icon={AlertTriangle} size={18} />
                <div>
                  <strong>Context Unavailable</strong>
                  <p>{err}</p>
                </div>
              </div>
            {:else if !snap}
              <div class="settings-loading">
                <Icon icon={Brain} size={24} />
                <span>Reading assistant context and active memory…</span>
              </div>
            {:else}
              <!-- Unified Apple Memory Health Meter (Zero Duplicates) -->
              <div class="prompt-memory-card">
                <div class="memory-card-header">
                  <div class="memory-title-wrap">
                    <span class="memory-card-title">Memory Capacity</span>
                    <span class="memory-card-sub">
                      ~{fmtTokens(categoryStats.total)} tokens used ({memoryPct}% capacity) · 
                      <span style={`color: ${memoryStatus.color}; font-weight: 550;`}>{memoryStatus.text}</span>
                    </span>
                  </div>
                </div>

                <!-- Multi-Segmented Proportional Memory Track -->
                <div class="memory-track" aria-label="Context memory breakdown">
                  {#if categoryStats.instructions > 0}
                    <div
                      class="memory-segment seg-instructions"
                      style={`width: ${(categoryStats.instructions / Math.max(1, categoryStats.total)) * 100}%;`}
                      title={`Instructions: ~${fmtTokens(categoryStats.instructions)} tokens`}
                    ></div>
                  {/if}
                  {#if categoryStats.project > 0}
                    <div
                      class="memory-segment seg-project"
                      style={`width: ${(categoryStats.project / Math.max(1, categoryStats.total)) * 100}%;`}
                      title={`Project Knowledge: ~${fmtTokens(categoryStats.project)} tokens`}
                    ></div>
                  {/if}
                  {#if categoryStats.conversation > 0}
                    <div
                      class="memory-segment seg-conversation"
                      style={`width: ${(categoryStats.conversation / Math.max(1, categoryStats.total)) * 100}%;`}
                      title={`Conversation: ~${fmtTokens(categoryStats.conversation)} tokens`}
                    ></div>
                  {/if}
                  {#if categoryStats.capabilities > 0}
                    <div
                      class="memory-segment seg-capabilities"
                      style={`width: ${(categoryStats.capabilities / Math.max(1, categoryStats.total)) * 100}%;`}
                      title={`Capabilities: ~${fmtTokens(categoryStats.capabilities)} tokens`}
                    ></div>
                  {/if}
                </div>

                <!-- Interactive Category Pills -->
                <div class="memory-pills-row">
                  <button
                    type="button"
                    class={`memory-pill pill-instructions${activeCategory === "instructions" ? " active" : ""}`}
                    onclick={() => (activeCategory = activeCategory === "instructions" ? "all" : "instructions")}
                  >
                    <span class="pill-dot seg-instructions"></span>
                    <span class="pill-label">Instructions</span>
                    <span class="pill-stat">~{fmtTokens(categoryStats.instructions)}</span>
                  </button>
                  <button
                    type="button"
                    class={`memory-pill pill-project${activeCategory === "project" ? " active" : ""}`}
                    onclick={() => (activeCategory = activeCategory === "project" ? "all" : "project")}
                  >
                    <span class="pill-dot seg-project"></span>
                    <span class="pill-label">Project</span>
                    <span class="pill-stat">~{fmtTokens(categoryStats.project)}</span>
                  </button>
                  <button
                    type="button"
                    class={`memory-pill pill-conversation${activeCategory === "conversation" ? " active" : ""}`}
                    onclick={() => (activeCategory = activeCategory === "conversation" ? "all" : "conversation")}
                  >
                    <span class="pill-dot seg-conversation"></span>
                    <span class="pill-label">Chat</span>
                    <span class="pill-stat">~{fmtTokens(categoryStats.conversation)}</span>
                  </button>
                  <button
                    type="button"
                    class={`memory-pill pill-capabilities${activeCategory === "capabilities" ? " active" : ""}`}
                    onclick={() => (activeCategory = activeCategory === "capabilities" ? "all" : "capabilities")}
                  >
                    <span class="pill-dot seg-capabilities"></span>
                    <span class="pill-label">Tools</span>
                    <span class="pill-stat">~{fmtTokens(categoryStats.capabilities)}</span>
                  </button>
                </div>
              </div>

              <!-- Apple Reader Section Viewer -->
              <PromptInspectContent
                {activeRow}
                rawContent={activeRow ? inspectBody(activeRow) : ""}
              />
            {/if}
          </div>
        </div>
      </section>
    </div>
  </div>
</div>

// crates/z-engine-gui/ui/src/components/PromptInspector.tsx
import { useEffect, useMemo, useState } from "react";
import { ChevronLeft, Copy } from "../lib/icons";
import { inspectPrompt, type PromptInspect, type PromptPart, type PromptTool } from "../lib/commands";
import { sessionStore } from "../lib/events";
import { promptInsights } from "../lib/promptInsights";
import { fmtTokens } from "../lib/util";
import { PromptInspectChart } from "./PromptInspectChart";
import "./promptInspect.css";

type Row =
  | { key: string; kind: "msg"; part: PromptPart }
  | { key: string; kind: "tool"; tool: PromptTool };

function rowsOf(snap: PromptInspect): Row[] {
  return [
    ...snap.messages.map((part, i) => ({ key: `m-${i}`, kind: "msg" as const, part })),
    ...snap.tools.map((tool, i) => ({ key: `t-${i}`, kind: "tool" as const, tool })),
  ];
}

function bodyOf(row: Row): string {
  if (row.kind === "msg") return row.part.content;
  return `${row.tool.description}\n\n${row.tool.schema}`;
}

function copyText(snap: PromptInspect): string {
  const ins = promptInsights(snap);
  const chunks = [
    `model: ${snap.model}`,
    snap.sent ? "sent: yes" : "sent: preview / reconstructed",
    `tokens ≈ ${snap.totalTokens}`,
    `largest: ${ins.largest.name} (${Math.round(ins.largest.share * 100)}%)`,
    `stable prefix: ${ins.stablePrefix}`,
    `volatile tail: ${ins.volatileTail}`,
    "",
    "## Order (wire)",
    ...ins.layers.map(
      (l) => `${l.order}. ${l.label} [${l.role}] ~${l.tokens} tok (${Math.round(l.share * 100)}%)`,
    ),
    "",
    "## Hints",
    ...ins.hints.map((h) => `- ${h}`),
    "",
  ];
  for (const m of snap.messages) {
    chunks.push(`## ${m.label} (${m.role}, ~${m.tokens} tok)`, m.content, "");
  }
  if (snap.tools.length) {
    chunks.push("## Tools");
    for (const t of snap.tools) {
      chunks.push(`### ${t.name} (~${t.tokens} tok)`, t.description, t.schema, "");
    }
  }
  return chunks.join("\n");
}

function pct(n: number): string {
  return `${Math.round(n * 100)}%`;
}

/** Case-study view of the last (or restored) chat-completion request. */
export function PromptInspector({ onClose }: { onClose: () => void }) {
  const [snap, setSnap] = useState<PromptInspect | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [sel, setSel] = useState(0);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const id = sessionStore.getSnapshot() || undefined;
    inspectPrompt(id)
      .then((s) => {
        setSnap(s);
        setErr(null);
      })
      .catch((e: unknown) => {
        setErr(String(e).replace(/^Error:\s*/, ""));
      });
  }, []);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  const rows = useMemo(() => (snap ? rowsOf(snap) : []), [snap]);
  const ins = useMemo(() => (snap ? promptInsights(snap) : null), [snap]);
  const active = rows[sel] ?? rows[0];

  async function onCopy() {
    if (!snap) return;
    try {
      await navigator.clipboard.writeText(copyText(snap));
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1200);
    } catch (e) {
      console.error(e);
    }
  }

  return (
    <div className="prompt-inspect" role="dialog" aria-label="Prompt inspector">
      <header className="prompt-inspect-head">
        <button type="button" className="prompt-inspect-back" onClick={onClose}>
          <ChevronLeft size={15} />
          Back
        </button>
        <div className="prompt-inspect-title">
          <strong>Prompt assembly</strong>
          <span>
            {snap
              ? snap.sent
                ? "Wire order, budget share, and optimization hints"
                : "Preview — L0 + tools until a turn is sent"
              : "Loading…"}
          </span>
        </div>
        <button
          type="button"
          className="prompt-inspect-copy"
          onClick={() => void onCopy()}
          disabled={!snap}
        >
          <Copy size={12} />
          {copied ? "Copied" : "Copy study"}
        </button>
      </header>
      {err && <p className="prompt-inspect-err">{err}</p>}
      {snap && ins && (
        <>
          <div className="prompt-inspect-overview">
            <div className="prompt-overview-card">
              <em>Active Model</em>
              <strong>{snap.model}</strong>
            </div>
            <div className="prompt-overview-card">
              <em>Total Request</em>
              <strong>
                ~{fmtTokens(snap.totalTokens)} ({snap.messages.length} msgs · {snap.tools.length} tools)
              </strong>
            </div>
            <div className="prompt-overview-card">
              <em>Largest Sink</em>
              <strong title={ins.largest.name}>
                {ins.largest.name} · {pct(ins.largest.share)}
              </strong>
            </div>
            <div className="prompt-overview-card">
              <em>Cache Stability</em>
              <strong>{ins.stablePrefix} stable</strong>
            </div>
          </div>
          <PromptInspectChart ins={ins} />
          {ins.hints.length > 0 && (
            <ul className="prompt-inspect-hints">
              {ins.hints.map((h) => (
                <li key={h}>{h}</li>
              ))}
            </ul>
          )}
          <div className="prompt-inspect-body">
            <nav className="prompt-inspect-nav" aria-label="Prompt parts">
              {rows.map((row, i) => {
                const layer = ins.layers[i];
                const label = row.kind === "msg" ? row.part.label : row.tool.name;
                const hint = row.kind === "msg" ? row.part.role : "tool def";
                const tokens = row.kind === "msg" ? row.part.tokens : row.tool.tokens;
                return (
                  <button
                    key={row.key}
                    type="button"
                    className={i === sel ? "active" : ""}
                    onClick={() => setSel(i)}
                  >
                    <em>
                      <span className="prompt-ord">{layer?.order ?? i + 1}</span>
                      {label}
                    </em>
                    <span>
                      {hint}
                      <i
                        className="prompt-share"
                        style={{ width: pct(layer?.share ?? 0) }}
                      />
                    </span>
                    <strong>{fmtTokens(tokens)}</strong>
                  </button>
                );
              })}
            </nav>
            <div className="prompt-inspect-pane">
              {ins.layers[sel] && (
                <div className="prompt-part-stats">
                  <span className="stat-badge">~{fmtTokens(ins.layers[sel].tokens)}</span>
                  <span className="stat-badge">{ins.layers[sel].chars.toLocaleString()} chars</span>
                  <span className="stat-badge">{ins.layers[sel].lines} lines</span>
                  <span className="stat-badge">{pct(ins.layers[sel].share)} of budget</span>
                  <span className={`stat-badge ${ins.layers[sel].cacheable ? "cacheable" : "volatile"}`}>
                    {ins.layers[sel].cacheable ? "Cacheable" : "Volatile"}
                  </span>
                  <span className="stat-badge">Wire #{ins.layers[sel].order}</span>
                </div>
              )}
              <pre className="prompt-inspect-content">{active ? bodyOf(active) : ""}</pre>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
