// crates/z-engine-gui/ui/src/components/chrome/TopBar.svelte
<script lang="ts">
  import Icon, { FolderGit2, GitCompare, PanelLeft, Search } from "$lib/ui/icons";
  import { isMacPlatform, modLabel } from "$lib/platform";
  import ContextMeter from "./ContextMeter.svelte";
  import LogoMark from "./LogoMark.svelte";
  import UpdateButton from "./UpdateButton.svelte";
  import WindowControlsMaybe from "./WindowControlsMaybe.svelte";

  type Props = {
    title: string;
    titleHint?: string;
    diffOpen: boolean;
    sidebarOpen: boolean;
    onToggleSidebar: () => void;
    onPalette: () => void;
    onToggleDiff: () => void;
    onInspectPrompt?: () => void;
  };

  let {
    title,
    titleHint,
    diffOpen,
    sidebarOpen,
    onToggleSidebar,
    onPalette,
    onToggleDiff,
    onInspectPrompt,
  }: Props = $props();

  const isMac = isMacPlatform();
</script>

<header class="app-topbar" data-tauri-drag-region>
  <div class="topbar-left" data-tauri-drag-region>
    {#if !isMac}
      <div class="topbar-brand" title="Z Engine">
        <LogoMark size={15} />
        <span>Z Engine</span>
      </div>
    {/if}
    <button
      type="button"
      class="icon-btn"
      title={sidebarOpen ? `Hide sidebar (${modLabel()}B)` : `Show sidebar (${modLabel()}B)`}
      onclick={onToggleSidebar}
    >
      <Icon icon={PanelLeft} size={14} strokeWidth={1.8} />
    </button>
    <button
      type="button"
      class="topbar-workspace-pill"
      title={titleHint || "Open quick switcher"}
      onclick={onPalette}
    >
      <Icon icon={FolderGit2} size={13} class="topbar-ws-icon" strokeWidth={1.8} />
      <span class="topbar-ws-name">{title}</span>
    </button>
  </div>

  <div class="topbar-center" data-tauri-drag-region>
    <button
      type="button"
      class="topbar-search-bar"
      title={`Search & commands (${modLabel()}K)`}
      onclick={onPalette}
    >
      <Icon icon={Search} size={13} class="topbar-search-icon" strokeWidth={1.8} />
      <span class="topbar-search-text">Search chats, workspaces, commands…</span>
      <kbd class="topbar-search-kbd">{modLabel()}K</kbd>
    </button>
  </div>

  <div class="topbar-right" data-tauri-drag-region>
    <UpdateButton />
    <ContextMeter onInspect={onInspectPrompt} />
    <button
      type="button"
      class={`icon-btn${diffOpen ? " active" : ""}`}
      title="Review uncommitted git changes vs HEAD"
      onclick={onToggleDiff}
    >
      <Icon icon={GitCompare} size={14} strokeWidth={1.8} />
    </button>
    <WindowControlsMaybe />
  </div>
</header>

// crates/z-engine-gui/ui/src/components/TopBar.tsx
import { FolderGit2, GitCompare, PanelLeft, Search, Settings } from "lucide-react";
import { ContextMeter } from "./ContextMeter";
import { UpdateButton } from "./UpdateButton";
import { WindowControlsMaybe } from "./WindowControls";
import { LogoMark } from "./LogoMark";
import { isMacPlatform, modLabel } from "../lib/platform";

export function TopBar({
  title,
  titleHint,
  diffOpen,
  sidebarOpen,
  onToggleSidebar,
  onPalette,
  onToggleDiff,
  onSettings,
}: {
  title: string;
  titleHint?: string;
  diffOpen: boolean;
  sidebarOpen: boolean;
  onToggleSidebar: () => void;
  onPalette: () => void;
  onToggleDiff: () => void;
  onSettings: () => void;
}) {
  const isMac = isMacPlatform();

  return (
    <header className="app-topbar" data-tauri-drag-region>
      <div className="topbar-left" data-tauri-drag-region>
        {!isMac && (
          <div className="topbar-brand" title="Z Engine">
            <LogoMark size={15} />
            <span>Z Engine</span>
          </div>
        )}
        <button
          type="button"
          className="icon-btn"
          title={
            sidebarOpen ? `Hide sidebar (${modLabel()}B)` : `Show sidebar (${modLabel()}B)`
          }
          onClick={onToggleSidebar}
        >
          <PanelLeft size={14} strokeWidth={1.8} />
        </button>
        <button
          type="button"
          className="topbar-workspace-pill"
          title={titleHint || "Open quick switcher"}
          onClick={onPalette}
        >
          <FolderGit2 size={13} className="topbar-ws-icon" strokeWidth={1.8} />
          <span className="topbar-ws-name">{title}</span>
        </button>
      </div>

      <div className="topbar-center" data-tauri-drag-region>
        <button
          type="button"
          className="topbar-search-bar"
          title={`Search & commands (${modLabel()}K)`}
          onClick={onPalette}
        >
          <Search size={13} className="topbar-search-icon" strokeWidth={1.8} />
          <span className="topbar-search-text">Search chats, workspaces, commands…</span>
          <kbd className="topbar-search-kbd">{modLabel()}K</kbd>
        </button>
      </div>

      <div className="topbar-right" data-tauri-drag-region>
        <UpdateButton />
        <ContextMeter />
        <button
          type="button"
          className={`icon-btn${diffOpen ? " active" : ""}`}
          title="Review uncommitted git changes vs HEAD"
          onClick={onToggleDiff}
        >
          <GitCompare size={14} strokeWidth={1.8} />
        </button>
        <button
          type="button"
          className="icon-btn"
          title="Settings"
          onClick={onSettings}
        >
          <Settings size={14} strokeWidth={1.8} />
        </button>
        <WindowControlsMaybe />
      </div>
    </header>
  );
}
