// crates/z-engine-gui/ui/src/components/UserCard.tsx
import { useState, useSyncExternalStore } from "react";
import { Check, Copy, Undo2 } from "../lib/icons";
import { abort, revertToTurn } from "../lib/commands";
import { busyStore, draftStore, pushToast, trimTranscript, type Msg } from "../lib/events";

const COLLAPSE_CHARS = 380;
const COLLAPSE_LINES = 6;

/** Premium user prompt bubble with discrete micro-actions positioned below. */
export function UserCard({ m }: { m: Msg }) {
  const busy = useSyncExternalStore(busyStore.subscribe, () => busyStore.getSnapshot());
  const [copied, setCopied] = useState(false);
  const [pending, setPending] = useState(false);
  const lines = m.text.split("\n").length;
  const isLong = m.text.length > COLLAPSE_CHARS || lines > COLLAPSE_LINES;
  const [expanded, setExpanded] = useState(!isLong);

  async function copy() {
    try {
      await navigator.clipboard.writeText(m.text);
      setCopied(true);
      setTimeout(() => setCopied(false), 1200);
    } catch {
      pushToast("Copy failed", "warn");
    }
  }

  const canRevert = typeof m.runTurn === "number";

  async function revert() {
    if (!canRevert || pending) return;
    setPending(true);
    try {
      if (busy) await abort();
      draftStore.set(m.text);
      trimTranscript(m.runTurn as number);
      await revertToTurn(m.runTurn as number);
    } catch (e) {
      console.error(e);
      pushToast("Could not restore that prompt", "warn");
    } finally {
      setPending(false);
    }
  }

  return (
    <div className="user-message-row" id={`msg-${m.id}`} data-msg-id={m.id}>
      <div className="user-message-wrapper">
        {/* Main User Prompt Bubble */}
        <div className="user-message-bubble">
          <div className={`user-prompt-text${isLong && !expanded ? " collapsed" : ""}`}>
            {m.text}
          </div>

          {m.images && m.images.length > 0 && (
            <div className="user-attached-images">
              {m.images.map((url, i) => (
                <img key={i} src={url} alt={`attached ${i + 1}`} className="user-img-thumb" />
              ))}
            </div>
          )}

          {isLong && (
            <button
              type="button"
              className="user-expand-btn"
              onClick={() => setExpanded((v) => !v)}
            >
              {expanded ? "Show less" : "Show more"}
            </button>
          )}
        </div>

        {/* Micro-Actions Below the Chat Bubble (Hover Only, Minimalist Icon Buttons) */}
        <div className="user-bubble-actions">
          <button
            type="button"
            className={`bubble-action-icon-btn${copied ? " ok" : ""}`}
            title={copied ? "Copied" : "Copy prompt"}
            onClick={() => void copy()}
            aria-label="Copy prompt"
          >
            {copied ? (
              <Check size={12} strokeWidth={2} className="copy-ok" />
            ) : (
              <Copy size={12} strokeWidth={1.8} />
            )}
          </button>

          {canRevert && (
            <button
              type="button"
              className="bubble-action-icon-btn"
              disabled={pending}
              title={busy ? "Stop & edit prompt" : "Revert & edit prompt"}
              onClick={() => void revert()}
              aria-label="Revert & edit prompt"
            >
              <Undo2 size={12} strokeWidth={1.8} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

// crates/z-engine-gui/ui/src/components/chat/UserCard.svelte
<script lang="ts">
  import { abort, revertToTurn } from "$lib/commands";
  import { busyStore, draftStore, pushToast, trimTranscript } from "$lib/runtime";
  import { bindStore } from "$lib/svelte/bind.svelte";
  import type { Msg } from "$lib/types";
  import Icon, { Check, Copy, Undo2 } from "$lib/ui/icons";

  const COLLAPSE_CHARS = 380;
  const COLLAPSE_LINES = 6;

  type Props = { m: Msg };
  let { m }: Props = $props();

  const busy = bindStore(busyStore);
  let copied = $state(false);
  let pending = $state(false);
  const lines = $derived(m.text.split("\n").length);
  const isLong = $derived(m.text.length > COLLAPSE_CHARS || lines > COLLAPSE_LINES);
  let expanded = $state(true);

  async function copy() {
    try {
      await navigator.clipboard.writeText(m.text);
      copied = true;
      setTimeout(() => {
        copied = false;
      }, 1200);
    } catch {
      pushToast("Copy failed", "warn");
    }
  }

  const canRevert = $derived(typeof m.runTurn === "number");

  async function revert() {
    if (!canRevert || pending) return;
    pending = true;
    try {
      if (busy.current) await abort();
      draftStore.set(m.text);
      trimTranscript(m.runTurn as number);
      await revertToTurn(m.runTurn as number);
    } catch (e) {
      console.error(e);
      pushToast("Could not restore that prompt", "warn");
    } finally {
      pending = false;
    }
  }
</script>

<div class="user-message-row" id={`msg-${m.id}`} data-msg-id={m.id}>
  <div class="user-message-wrapper">
    <div class="user-message-bubble">
      <div class={`user-prompt-text${isLong && !expanded ? " collapsed" : ""}`}>
        {m.text}
      </div>
      {#if m.images && m.images.length > 0}
        <div class="user-attached-images">
          {#each m.images as url, i}
            <img src={url} alt={`attached ${i + 1}`} class="user-img-thumb" />
          {/each}
        </div>
      {/if}
      {#if isLong}
        <button type="button" class="user-expand-btn" onclick={() => (expanded = !expanded)}>
          {expanded ? "Show less" : "Show more"}
        </button>
      {/if}
    </div>
    <div class="user-bubble-actions">
      <button
        type="button"
        class={`bubble-action-icon-btn${copied ? " ok" : ""}`}
        title={copied ? "Copied" : "Copy prompt"}
        onclick={() => void copy()}
        aria-label="Copy prompt"
      >
        {#if copied}
          <Icon icon={Check} size={12} strokeWidth={2} class="copy-ok" />
        {:else}
          <Icon icon={Copy} size={12} strokeWidth={1.8} />
        {/if}
      </button>
      {#if canRevert}
        <button
          type="button"
          class="bubble-action-icon-btn"
          disabled={pending}
          title={busy.current ? "Stop & edit prompt" : "Revert & edit prompt"}
          onclick={() => void revert()}
          aria-label="Revert & edit prompt"
        >
          <Icon icon={Undo2} size={12} strokeWidth={1.8} />
        </button>
      {/if}
    </div>
  </div>
</div>
