// crates/z-engine-gui/ui/src/components/settings/AboutTab.tsx
import { useSyncExternalStore } from "react";
import {
  ArrowRight,
  CheckCircle2,
  Download,
  ExternalLink,
  LoaderCircle,
  RefreshCw,
  Sparkles,
} from "../../lib/icons";
import { LogoMark } from "../LogoMark";
import type { HarnessConfig } from "../../lib/commands";
import { updateStore } from "../../lib/updateStore";

function fmtBytes(bytes: number): string {
  if (bytes < 1024 * 1024) {
    return `${Math.round(bytes / 1024)} KB`;
  }
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

export function AboutTab({ cfg }: { cfg: HarnessConfig }) {
  const { info, checking, installing, progress } = useSyncExternalStore(
    updateStore.subscribe,
    () => updateStore.getSnapshot(),
  );

  const pct = progress?.percentage != null ? Math.round(progress.percentage) : null;
  const isInstalling =
    installing && (progress?.phase === "installing" || progress?.phase === "ready");

  return (
    <div className="tab-body about-tab">
      <div className="about-hero">
        <LogoMark size={44} />
        <div className="about-hero-text">
          <h3>Z Engine</h3>
          <p className="form-note">
            The Autonomous AI Coding Engine · v{cfg.version ?? "1.3.0"}
          </p>
        </div>
      </div>

      {info?.available ? (
        <div className="settings-update-card" role="status">
          <div className="settings-update-head">
            <div className="settings-update-badge">
              <Sparkles size={15} />
            </div>
            <div className="settings-update-info">
              <div className="settings-update-title">Update Available</div>
              <div className="settings-update-versions">
                <span className="ver-current">v{info.current}</span>
                <ArrowRight size={11} className="ver-arrow" />
                <span className="ver-target">v{info.latest}</span>
              </div>
            </div>
            <button
              type="button"
              className="settings-update-primary-btn"
              disabled={installing}
              onClick={() => void updateStore.install()}
            >
              {installing ? (
                <>
                  <LoaderCircle size={13} className="spin" />
                  <span>Installing…</span>
                </>
              ) : (
                <>
                  <Download size={13} />
                  <span>Update & Restart</span>
                </>
              )}
            </button>
          </div>

          {info.releaseNotes && (
            <div className="settings-update-notes">
              <div className="settings-notes-label">What's New in v{info.latest}</div>
              <div className="settings-notes-content">{info.releaseNotes}</div>
            </div>
          )}

          {installing && (
            <div className="settings-update-progress">
              <div className="settings-progress-labels">
                <span className="settings-phase-text">
                  {isInstalling
                    ? "Applying update & restarting…"
                    : "Downloading update package…"}
                </span>
                <span className="settings-pct-text">{pct != null ? `${pct}%` : ""}</span>
              </div>
              <div className="settings-progress-track">
                <div
                  className={`settings-progress-bar${
                    pct == null ? " indeterminate" : ""
                  }`}
                  style={{ width: `${pct ?? 30}%` }}
                />
              </div>
              {progress?.totalBytes != null && progress.totalBytes > 0 && (
                <div className="settings-bytes-counter">
                  {fmtBytes(progress.downloadedBytes)} / {fmtBytes(progress.totalBytes)}
                </div>
              )}
            </div>
          )}

          {info.url && (
            <div className="settings-update-footer">
              <button
                type="button"
                className="settings-github-link"
                onClick={() => updateStore.openRelease()}
              >
                <ExternalLink size={12} />
                <span>View Release on GitHub</span>
              </button>
            </div>
          )}
        </div>
      ) : (
        <div className="settings-uptodate-card">
          <div className="uptodate-left">
            <CheckCircle2 size={16} className="uptodate-icon" />
            <div className="uptodate-text">
              <strong>Z Engine is up to date</strong>
              <span>Version {cfg.version ?? "1.3.0"} is the latest version available.</span>
            </div>
          </div>
          <button
            type="button"
            className="update-check"
            disabled={checking}
            onClick={() => void updateStore.check(true)}
          >
            <RefreshCw size={12} className={checking ? "spin" : undefined} />
            {checking ? "Checking…" : "Check Now"}
          </button>
        </div>
      )}

      <div className="about-section-divider" />

      <h4 className="about-paths-title">System Paths & Configuration</h4>
      <dl className="about-dl">
        <dt>Global Config</dt>
        <dd>
          <code>~/.config/z-engine/config.toml</code>
          <span className="form-note"> created on first launch · API key in auth.json</span>
        </dd>
        <dt>Project Config</dt>
        <dd>
          <code>.z-engine/config.toml</code>
        </dd>
        <dt>Session Store</dt>
        <dd>
          <code>Application Support/z-engine/sessions</code>
        </dd>
        <dt>Active Model</dt>
        <dd>
          <code>{cfg.model}</code>
        </dd>
      </dl>
    </div>
  );
}

// crates/z-engine-gui/ui/src/components/settings/AboutTab.svelte
<script lang="ts">
  import type { HarnessConfig } from "$lib/commands";
  import { bindStore } from "$lib/svelte/bind.svelte";
  import { updateStore } from "$lib/updateStore";
  import Icon, {
    ArrowRight,
    CheckCircle2,
    Download,
    ExternalLink,
    LoaderCircle,
    RefreshCw,
    Sparkles,
  } from "$lib/ui/icons";
  import LogoMark from "../chrome/LogoMark.svelte";

  type Props = { cfg: HarnessConfig };
  let { cfg }: Props = $props();

  const update = bindStore(updateStore);
  const info = $derived(update.current.info);
  const checking = $derived(update.current.checking);
  const installing = $derived(update.current.installing);
  const progress = $derived(update.current.progress);
  const pct = $derived(progress?.percentage != null ? Math.round(progress.percentage) : null);
  const isInstalling = $derived(
    installing && (progress?.phase === "installing" || progress?.phase === "ready"),
  );
</script>

<div class="tab-body about-tab">
  <div class="about-hero">
    <LogoMark size={44} />
    <div class="about-hero-text">
      <h3>Z Engine</h3>
      <p class="form-note">The Autonomous AI Coding Engine · v{cfg.version ?? "1.3.0"}</p>
    </div>
  </div>

  {#if info?.available}
    <div class="settings-update-card" role="status">
      <div class="settings-update-head">
        <div class="settings-update-badge">
          <Icon icon={Sparkles} size={15} />
        </div>
        <div class="settings-update-info">
          <div class="settings-update-title">Update Available</div>
          <div class="settings-update-versions">
            <span class="ver-current">v{info.current}</span>
            <Icon icon={ArrowRight} size={11} class="ver-arrow" />
            <span class="ver-target">v{info.latest}</span>
          </div>
        </div>
        <button
          type="button"
          class="settings-update-primary-btn"
          disabled={installing}
          onclick={() => void updateStore.install()}
        >
          {#if installing}
            <Icon icon={LoaderCircle} size={13} class="spin" />
            <span>{isInstalling && pct != null ? `Installing… ${pct}%` : "Installing…"}</span>
          {:else}
            <Icon icon={Download} size={13} />
            <span>Update & Restart</span>
          {/if}
        </button>
      </div>
      {#if info.releaseNotes}
        <div class="settings-update-notes">
          <div class="settings-notes-label">What's New in v{info.latest}</div>
          <div class="settings-notes-content">{info.releaseNotes}</div>
        </div>
      {/if}
      {#if info.url}
        <div class="settings-update-footer">
          <button type="button" class="settings-github-link" onclick={() => updateStore.openRelease()}>
            <Icon icon={ExternalLink} size={12} />
            <span>View Release on GitHub</span>
          </button>
        </div>
      {/if}
    </div>
  {:else}
    <div class="settings-uptodate-card">
      <div class="uptodate-left">
        <Icon icon={CheckCircle2} size={16} class="uptodate-icon" />
        <div class="uptodate-text">
          <strong>Z Engine is up to date</strong>
          <span>Version {cfg.version ?? "1.3.0"} is the latest version available.</span>
        </div>
      </div>
      <button
        type="button"
        class="update-check"
        disabled={checking}
        onclick={() => void updateStore.check(true)}
      >
        <Icon icon={RefreshCw} size={12} class={checking ? "spin" : undefined} />
        {checking ? "Checking…" : "Check Now"}
      </button>
    </div>
  {/if}

  <div class="about-section-divider"></div>
  <h4 class="about-paths-title">System Paths & Configuration</h4>
  <dl class="about-dl">
    <dt>Global Config</dt>
    <dd>
      <code>~/.config/z-engine/config.toml</code>
      <span class="form-note"> created on first launch · API key in auth.json</span>
    </dd>
    <dt>Project Config</dt>
    <dd><code>.z-engine/config.toml</code></dd>
    <dt>Session Store</dt>
    <dd><code>Application Support/z-engine/sessions</code></dd>
    <dt>Active Model</dt>
    <dd><code>{cfg.model}</code></dd>
  </dl>
</div>
