// crates/z-engine-gui/ui/src/components/settings/PermissionsTab.svelte
<script lang="ts">
  import { listPermissionRules, removePermissionRule, savePermissionRule } from "$lib/commands";

  let rules = $state<string[]>([]);
  let draft = $state("");

  $effect(() => {
    listPermissionRules()
      .then((r) => {
        rules = r;
      })
      .catch(() => {
        rules = [];
      });
  });

  async function add() {
    const rule = draft.trim();
    if (!rule) return;
    await savePermissionRule(rule);
    draft = "";
    rules = await listPermissionRules();
  }

  async function remove(rule: string) {
    await removePermissionRule(rule);
    rules = await listPermissionRules();
  }
</script>

<div class="tab-body">
  <section class="settings-group">
    <h3>Allow rules</h3>
    <p class="form-note">Bash prefixes that skip approval.</p>
    <ul class="rule-list">
      {#each rules as r}
        <li>
          <code>{r}</code>
          <button class="mini" title={`Remove ${r}`} onclick={() => void remove(r)}>✕</button>
        </li>
      {/each}
      {#if rules.length === 0}
        <li class="none">No rules yet.</li>
      {/if}
    </ul>
    <form
      class="inline-form"
      onsubmit={(e) => {
        e.preventDefault();
        void add();
      }}
    >
      <input bind:value={draft} placeholder='e.g. "cargo test*"' spellcheck={false} />
      <button type="submit" disabled={!draft.trim()}>Add rule</button>
    </form>
  </section>
</div>

// crates/z-engine-gui/ui/src/components/settings/PermissionsTab.tsx
import { useEffect, useState } from "react";
import { listPermissionRules, removePermissionRule, savePermissionRule } from "../../lib/commands";

export function PermissionsTab() {
  const [rules, setRules] = useState<string[]>([]);
  const [draft, setDraft] = useState("");

  useEffect(() => {
    listPermissionRules()
      .then(setRules)
      .catch(() => setRules([]));
  }, []);

  async function add() {
    const rule = draft.trim();
    if (!rule) return;
    await savePermissionRule(rule);
    setDraft("");
    setRules(await listPermissionRules());
  }

  async function remove(rule: string) {
    await removePermissionRule(rule);
    setRules(await listPermissionRules());
  }

  return (
    <div className="tab-body">
      <section className="settings-group">
        <h3>Allow rules</h3>
        <p className="form-note">Bash prefixes that skip approval.</p>
        <ul className="rule-list">
        {rules.map((r) => (
          <li key={r}>
            <code>{r}</code>
            <button className="mini" title={`Remove ${r}`} onClick={() => void remove(r)}>
              ✕
            </button>
          </li>
        ))}
        {rules.length === 0 && <li className="none">No rules yet.</li>}
      </ul>
      <form
        className="inline-form"
        onSubmit={(e) => {
          e.preventDefault();
          void add();
        }}
      >
        <input
          value={draft}
          onChange={(e) => setDraft(e.currentTarget.value)}
          placeholder='e.g. "cargo test*"'
          spellCheck={false}
        />
        <button type="submit" disabled={!draft.trim()}>
          Add rule
        </button>
      </form>
      </section>
    </div>
  );
}
