// crates/z-engine-gui/ui/src/components/settings/SettingsPage.tsx
import { useEffect, useState, useSyncExternalStore } from "react";
import { ChevronLeft, Coins, Info, Server, Settings, Shield } from "lucide-react";
import { getConfig, type HarnessConfig } from "../../lib/commands";
import { updateStore } from "../../lib/updateStore";
import { LogoMark } from "../LogoMark";
import { AboutTab } from "./AboutTab";
import { CostTab } from "./CostTab";
import { GeneralTab } from "./GeneralTab";
import { McpTab } from "./McpTab";
import { PermissionsTab } from "./PermissionsTab";
import "../../settings.css";

type Tab = "general" | "permissions" | "mcp" | "cost" | "about";

const TABS: Array<{ id: Tab; label: string; hint: string; icon: typeof Settings }> = [
  { id: "general", label: "General", hint: "Model and context", icon: Settings },
  { id: "permissions", label: "Permissions", hint: "Bash allow rules", icon: Shield },
  { id: "mcp", label: "MCP servers", hint: "External tools", icon: Server },
  { id: "cost", label: "Cost", hint: "Token pricing", icon: Coins },
  { id: "about", label: "About", hint: "Paths and version", icon: Info },
];

export function SettingsPage({ onClose }: { onClose: () => void }) {
  const [tab, setTab] = useState<Tab>("general");
  const [cfg, setCfg] = useState<HarnessConfig | null>(null);
  const update = useSyncExternalStore(updateStore.subscribe, () => updateStore.getSnapshot());
  const current = TABS.find((t) => t.id === tab);

  useEffect(() => {
    getConfig().then(setCfg).catch(console.error);
  }, []);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div className="settings-page" role="dialog" aria-label="Settings">
      <nav className="settings-nav">
        <button type="button" className="settings-back" onClick={onClose}>
          <ChevronLeft size={15} />
          <span>Back</span>
        </button>
        <div className="settings-brand">
          <LogoMark size={18} />
          <span>Settings</span>
        </div>
        {TABS.map((t) => {
          const Icon = t.icon;
          return (
            <button
              key={t.id}
              className={`settings-nav-item${tab === t.id ? " active" : ""}`}
              onClick={() => setTab(t.id)}
            >
              <Icon size={15} />
              <span className="settings-nav-copy">
                <strong>
                  {t.label}
                  {t.id === "about" && update.info?.available && (
                    <span className="update-dot inline" role="status" aria-label="Update available" />
                  )}
                </strong>
                <em>{t.hint}</em>
              </span>
            </button>
          );
        })}
      </nav>
      <div className="settings-main">
        <header className="settings-head">
          <div>
            <h2>{current?.label}</h2>
            <p className="settings-sub">{current?.hint}</p>
          </div>
        </header>
        {!cfg && <div className="tab-body">Loading…</div>}
        {cfg && tab === "general" && <GeneralTab key="g" cfg={cfg} />}
        {cfg && tab === "permissions" && <PermissionsTab key="p" />}
        {cfg && tab === "mcp" && <McpTab key="m" />}
        {cfg && tab === "cost" && <CostTab key="c" cfg={cfg} />}
        {cfg && tab === "about" && <AboutTab key="a" cfg={cfg} />}
      </div>
    </div>
  );
}

// crates/z-engine-gui/ui/src/components/settings/SettingsPage.svelte
<script lang="ts">
  import { getConfig, type HarnessConfig } from "$lib/commands";
  import { bindStore } from "$lib/svelte/bind.svelte";
  import { updateStore } from "$lib/updateStore";
  import Icon, { Info, Server, Shield, Sliders, X } from "$lib/ui/icons";
  import LogoMark from "../chrome/LogoMark.svelte";
  import AboutTab from "./AboutTab.svelte";
  import GeneralTab from "./GeneralTab.svelte";
  import McpTab from "./McpTab.svelte";
  import PermissionsTab from "./PermissionsTab.svelte";
  import "../../settings.css";

  type Tab = "general" | "permissions" | "mcp" | "about";
  type Props = { isClosing?: boolean; onClose: () => void };

  let { isClosing = false, onClose }: Props = $props();
  let tab = $state<Tab>("general");
  let cfg = $state<HarnessConfig | null>(null);
  const update = bindStore(updateStore);

  const tabs: Array<{ id: Tab; label: string; hint: string; icon: typeof Sliders }> = [
    { id: "general", label: "General", hint: "Provider & model", icon: Sliders },
    { id: "permissions", label: "Permissions", hint: "Allow rules", icon: Shield },
    { id: "mcp", label: "MCP", hint: "External tools", icon: Server },
    { id: "about", label: "About", hint: "Version & paths", icon: Info },
  ];

  const active = $derived(tabs.find((t) => t.id === tab) ?? tabs[0]);

  $effect(() => {
    void tab;
    getConfig()
      .then((c) => {
        cfg = c;
      })
      .catch(console.error);
  });

  $effect(() => {
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  });
</script>

<div
  class={`settings-overlay${isClosing ? " is-closing" : ""}`}
  role="presentation"
>
  <div
    class={`settings-page${isClosing ? " is-closing" : ""}`}
    role="dialog"
    tabindex="-1"
    aria-label="Settings"
  >
    <aside class="settings-rail">
      <div class="settings-brand">
        <LogoMark size={22} />
        <div>
          <strong>Settings</strong>
          <span>Z Engine</span>
        </div>
      </div>
      <nav class="settings-nav" aria-label="Settings sections">
        {#each tabs as t}
          <button
            type="button"
            class={`settings-nav-btn${tab === t.id ? " active" : ""}`}
            onclick={() => (tab = t.id)}
          >
            <span class="settings-nav-icon">
              <Icon icon={t.icon} size={14} />
            </span>
            <span class="settings-nav-copy">
              <em>{t.label}</em>
              <small>{t.hint}</small>
            </span>
            {#if t.id === "about" && update.current.info?.available}
              <span class="update-dot" role="status" aria-label="Update available"></span>
            {/if}
          </button>
        {/each}
      </nav>
      <div class="settings-rail-foot">
        <span>{cfg?.version ? `v${cfg.version}` : "Z Engine"}</span>
      </div>
    </aside>

    <section class="settings-main">
      <header class="settings-main-head">
        <div>
          <h2>{active.label}</h2>
          <p>{active.hint}</p>
        </div>
        <button type="button" class="settings-close" onclick={onClose} aria-label="Close settings">
          <Icon icon={X} size={14} />
          <kbd>Esc</kbd>
        </button>
      </header>
      <div class="settings-content-wrap">
        <div class="settings-content-body">
          {#if !cfg}
            <div class="settings-loading">Loading settings…</div>
          {:else if tab === "general"}
            <GeneralTab {cfg} />
          {:else if tab === "permissions"}
            <PermissionsTab />
          {:else if tab === "mcp"}
            <McpTab />
          {:else}
            <AboutTab {cfg} />
          {/if}
        </div>
      </div>
    </section>
  </div>
</div>
