// crates/z-engine-gui/ui/src/components/overlays/DiffPanel.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { diffForFile, listChangedFiles, type ChangedFile } from "$lib/commands";
  import { looksLikeDiff } from "$lib/diffParse";
  import { ChevronDown, ChevronRight, FileCode, Icon, RefreshCw, X } from "$lib/ui/icons";
  import DiffView from "./DiffView.svelte";

  type Props = {
    isClosing?: boolean;
    onClose: () => void;
  };

  let { isClosing = false, onClose }: Props = $props();

  let files = $state<ChangedFile[] | null>(null);
  let error = $state<string | null>(null);
  let openPath = $state<string | null>(null);
  let diff = $state("");
  let refreshing = $state(false);

  onMount(() => {
    let active = true;
    void listChangedFiles()
      .then((f) => {
        if (active) {
          files = f;
          error = null;
        }
      })
      .catch((e) => {
        if (active) error = String(e);
      });
    return () => {
      active = false;
    };
  });

  async function refresh() {
    refreshing = true;
    try {
      files = await listChangedFiles();
      error = null;
    } catch (e) {
      error = String(e);
    } finally {
      refreshing = false;
    }
  }

  async function toggle(path: string) {
    if (openPath === path) {
      openPath = null;
      return;
    }
    openPath = path;
    diff = "";
    try {
      diff = await diffForFile(path);
    } catch (e) {
      diff = `(no diff available: ${String(e)})`;
    }
  }
</script>

<aside class="diff-panel{isClosing ? ' is-closing' : ''}">
  <div class="diff-head">
    <div class="diff-head-left">
      <span class="diff-title">Workbench Changes</span>
      {#if files && files.length > 0}
        <span class="diff-count-badge">{files.length}</span>
      {/if}
    </div>
    <div class="diff-head-actions">
      <button
        type="button"
        class="icon-btn{refreshing ? ' spinning' : ''}"
        title="Refresh changes"
        onclick={() => void refresh()}
      >
        <Icon icon={RefreshCw} size={12} />
      </button>
      <button type="button" class="icon-btn" title="Close review pane" onclick={onClose}>
        <Icon icon={X} size={13} />
      </button>
    </div>
  </div>
  <div class="diff-body">
    {#if files === null && !error}
      <div class="sess-empty">Checking git status…</div>
    {/if}
    {#if error}
      <div class="sess-empty">Git status unavailable: {error}</div>
    {/if}
    {#if files?.length === 0}
      <div class="sess-empty">Working tree is clean — no modified files.</div>
    {/if}
    {#each files ?? [] as f (f.path)}
      {@const isOpen = openPath === f.path}
      <div class="diff-file{isOpen ? ' is-open' : ''}">
        <button
          type="button"
          class="diff-file-head status-{f.status}"
          onclick={() => void toggle(f.path)}
        >
          {#if isOpen}
            <Icon icon={ChevronDown} size={12} />
          {:else}
            <Icon icon={ChevronRight} size={12} />
          {/if}
          <Icon icon={FileCode} size={13} class="diff-file-icon" />
          <span class="diff-path">{f.path}</span>
          <span class="badge {f.status}">{f.status}</span>
        </button>
        {#if isOpen}
          {#if diff === ""}
            <pre class="diff-text">Loading diff…</pre>
          {:else if looksLikeDiff(diff)}
            <DiffView text={diff} />
          {:else}
            <pre class="diff-text">{diff}</pre>
          {/if}
        {/if}
      </div>
    {/each}
  </div>
</aside>

// crates/harness-gui/ui/src/components/DiffPanel.tsx
import { useEffect, useState } from "react";
import { X } from "lucide-react";
import { diffForFile, listChangedFiles, type ChangedFile } from "../lib/commands";

/** Codex-style review panel: working-tree changes vs HEAD, with a
 * unified diff per file (full content for untracked files). */
export function DiffPanel({ onClose }: { onClose: () => void }) {
  const [files, setFiles] = useState<ChangedFile[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [openPath, setOpenPath] = useState<string | null>(null);
  const [diff, setDiff] = useState<string>("");

  useEffect(() => {
    void listChangedFiles()
      .then((f) => setFiles(f))
      .catch((e) => setError(String(e)));
  }, []);

  async function toggle(path: string) {
    if (openPath === path) {
      setOpenPath(null);
      return;
    }
    setOpenPath(path);
    setDiff("");
    try {
      setDiff(await diffForFile(path));
    } catch (e) {
      setDiff(`(no diff available: ${String(e)})`);
    }
  }

  return (
    <aside className="diff-panel">
      <div className="diff-head">
        <span className="diff-title">Review changes</span>
        <button className="icon-btn" title="Close" onClick={onClose}>
          <X size={12} />
        </button>
      </div>
      <div className="diff-body">
        {files === null && !error && <div className="sess-empty">loading…</div>}
        {error && <div className="sess-empty">git unavailable: {error}</div>}
        {files?.length === 0 && (
          <div className="sess-empty">No changes in the working tree.</div>
        )}
        {files?.map((f) => (
          <div key={f.path} className="diff-file">
            <button
              className={`diff-file-head status-${f.status}`}
              onClick={() => void toggle(f.path)}
            >
              <span className={`badge ${f.status}`}>{f.status}</span>
              <span className="diff-path">{f.path}</span>
            </button>
            {openPath === f.path && (
              <pre className="diff-text">{diff || "…"}</pre>
            )}
          </div>
        ))}
      </div>
    </aside>
  );
}
