// crates/z-engine-gui/ui/src/components/SplashScreen.tsx
import { useEffect } from "react";
import "../splash.css";

const SPLASH_MS = 1400;
const BOOT_ID = "boot-splash";

/** Drives the HTML boot splash (in index.html) through its leave
 * animation. Does not mount a second splash — the first paint already
 * is the splash. */
export function SplashScreen({ onDone }: { onDone: () => void }) {
  useEffect(() => {
    const el = document.getElementById(BOOT_ID);
    const reduce =
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    if (!el) {
      onDone();
      return;
    }
    if (reduce) {
      el.remove();
      onDone();
      return;
    }

    const leaveAt = window.setTimeout(() => el.classList.add("leaving"), SPLASH_MS);
    const doneAt = window.setTimeout(() => {
      el.remove();
      onDone();
    }, SPLASH_MS + 320);
    return () => {
      window.clearTimeout(leaveAt);
      window.clearTimeout(doneAt);
    };
  }, [onDone]);

  return null;
}

// crates/z-engine-gui/ui/src/components/chrome/SplashScreen.svelte
<script lang="ts">
  import "../../splash.css";

  const HOLD_MS = 1100;
  const EXIT_MS = 420;
  const BOOT_ID = "boot-splash";

  type Props = { onDone: () => void };
  let { onDone }: Props = $props();

  $effect(() => {
    const el = document.getElementById(BOOT_ID);
    const reduce =
      typeof window !== "undefined" &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches;

    if (!el) {
      onDone();
      return;
    }
    if (reduce) {
      el.remove();
      onDone();
      return;
    }

    // Enhance the static HTML splash with wordmark + bar classes already in markup.
    el.classList.add("splash-live");
    const leaveAt = window.setTimeout(() => el.classList.add("leaving"), HOLD_MS);
    const doneAt = window.setTimeout(() => {
      el.remove();
      onDone();
    }, HOLD_MS + EXIT_MS);
    return () => {
      window.clearTimeout(leaveAt);
      window.clearTimeout(doneAt);
    };
  });
</script>
